# Source this file in your shell for this project session.
export MEMSEARCH_PROVIDER="local"
export MEMSEARCH_MODEL="BAAI/bge-m3"
export PM="/Users/pranay/Projects/projects-memory"
export PROJECT_REL="travel_agency_agent"
export AGENT_MOTTO_SOURCE="/Users/pranay/Downloads/motto_v3.md"
export PROJECT_MOTTO_FILE="/Users/pranay/Projects/travel_agency_agent/motto_v3.md"
export LEGACY_PROJECT_MOTTO_FILE="/Users/pranay/Projects/travel_agency_agent/motto_v2.md"
export AGENT_SESSION_CONTEXT="/Users/pranay/Projects/travel_agency_agent/Docs/context/agent-start/SESSION_CONTEXT.md"
export AGENT_KICKOFF_PROMPT="/Users/pranay/Projects/travel_agency_agent/Docs/context/agent-start/AGENT_KICKOFF_PROMPT.txt"
