# Source this file in your shell for this project session.
export MEMSEARCH_PROVIDER="local"
export MEMSEARCH_MODEL="BAAI/bge-m3"
export PM="/Users/pranay/Projects/projects-memory"
export PROJECT_REL="travel_agency_agent"
export AGENT_DOCTRINE_ROOT="/Users/pranay/Projects/agent-start/doctrines"
export AGENT_DOCTRINE_SOURCE="/Users/pranay/Projects/agent-start/doctrines/OPERATING_DOCTRINE.md"
export AGENT_DOCTRINE_VERSION="8.0"
export AGENT_DOCTRINE_SHA256="ff848618a7431a3b06c7409caa45683bd27c64263d45b93f9fcd36a89803466a"
export AGENT_DOCTRINE_MANIFEST="/Users/pranay/Projects/agent-start/doctrines/DOCTRINE_FAMILY_MANIFEST.json"
export AGENT_SELECTED_DOCTRINES="OPERATING_DOCTRINE.md"
export AGENT_SESSION_CONTEXT="/Users/pranay/Projects/travel_agency_agent/docs/context/agent-start/SESSION_CONTEXT.md"
export AGENT_KICKOFF_PROMPT="/Users/pranay/Projects/travel_agency_agent/docs/context/agent-start/AGENT_KICKOFF_PROMPT.txt"
