# Source this file in your shell for this project session.
export MEMSEARCH_PROVIDER="local"
export MEMSEARCH_MODEL="BAAI/bge-m3"
export PM="/Users/pranay/Projects/projects-memory"
export PROJECT_REL="travel_agency_agent/spine_api"
export AGENT_DOCTRINE_SOURCE="/Users/pranay/Downloads/OPERATING_DOCTRINE.md"
export AGENT_DOCTRINE_VERSION="6.1"
export AGENT_DOCTRINE_SHA256="5b3128861ce9408b1cfe3a4127b8ec6a709612411dcd777746c2e9f2288bf594"
export PROJECT_DOCTRINE_FILE="/Users/pranay/Projects/travel_agency_agent/spine_api/OPERATING_DOCTRINE.md"
export AGENT_SESSION_CONTEXT="/Users/pranay/Projects/travel_agency_agent/spine_api/docs/context/agent-start/SESSION_CONTEXT.md"
export AGENT_KICKOFF_PROMPT="/Users/pranay/Projects/travel_agency_agent/spine_api/docs/context/agent-start/AGENT_KICKOFF_PROMPT.txt"
