"use client";

import React, { useState } from "react";
import { useWorkbenchStore } from "@/stores/workbench";
import { ReviewControls } from "@/components/workspace/ReviewControls";
import { useTripContext } from "@/contexts/TripContext";
import type { PromptBundle } from "@/types/spine";
import type { Trip } from "@/lib/api-client";
import { CheckCircle, Send } from "lucide-react";
import styles from "@/app/workbench/workbench.module.css";

interface OutputPanelProps {
  trip?: Trip | null;
  tripId?: string;
}

/**
 * OutputPanel Workflow (Wave 5 & 8)
 * 
 * Surfaces final internal/external bundles generated by the spine.
 * Wave 8 adds review controls and delivery actions.
 */
export function OutputPanel({ trip: propTrip, tripId: propTripId }: OutputPanelProps) {
  // Try to get trip from context if prop not provided
  let context;
  try {
    context = useTripContext();
  } catch (e) {
    // Silently continue if context unavailable
  }

  const trip = propTrip || context?.trip || null;
  const tripId = propTripId || trip?.id || context?.tripId || "";

  const { result_internal_bundle, result_traveler_bundle, debug_raw_json, setDebugRawJson } = useWorkbenchStore();

  const [isSending, setIsSending] = useState(false);
  const [sendSuccess, setSendSuccess] = useState(false);

  // Fallback chain: Store (transient) > Trip (persisted)
  const internalBundle = (result_internal_bundle || trip?.internal_bundle) as PromptBundle | null;
  const travelerBundle = (result_traveler_bundle || trip?.traveler_bundle) as PromptBundle | null;

  const handleSendToCustomer = () => {
    setIsSending(true);
    // Mocking delivery for Wave 8
    setTimeout(() => {
      setIsSending(false);
      setSendSuccess(true);
      setTimeout(() => setSendSuccess(false), 5000);
    }, 1500);
  };

  if (!internalBundle && !travelerBundle) {
    return (
      <div className={styles.emptyState}>
        <p>No output data for trip {tripId}. Process a trip from the analysis pipeline first to generate response bundles.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8">
      {/* Review Workflow - Wave 8 */}
      {trip && (
        <ReviewControls 
          trip={trip} 
          onActionComplete={() => {
            // Parent/Context will handle data refresh
          }} 
        />
      )}

      {/* Internal vs Traveler-safe Split View */}
      <div className={styles.section}>
        <h3 className={styles.sectionTitle}>Agent View vs Customer View</h3>
        <div className={styles.splitView}>
          <div className={`${styles.splitPanel} ${styles.internalPanel}`}>
            <div className={styles.splitTitle}>For You (Agent)</div>
            {internalBundle ? (
              <div>
                <div style={{ marginBottom: "12px" }}>
                  <strong style={{ fontSize: "12px", color: "var(--color-text-muted)" }}>System Context</strong>
                  <p style={{ fontSize: "13px", whiteSpace: "pre-wrap", marginTop: "4px" }}>
                    {internalBundle.system_context || "—"}
                  </p>
                </div>
                <div style={{ marginBottom: "12px" }}>
                  <strong style={{ fontSize: "12px", color: "var(--color-text-muted)" }}>User Message</strong>
                  <p style={{ fontSize: "13px", whiteSpace: "pre-wrap", marginTop: "4px" }}>
                    {internalBundle.user_message || "—"}
                  </p>
                </div>
                {internalBundle.constraints && internalBundle.constraints.length > 0 && (
                  <div>
                    <strong style={{ fontSize: "12px", color: "var(--color-text-muted)" }}>Constraints</strong>
                    <ul style={{ margin: "4px 0 0 16px", fontSize: "12px" }}>
                      {internalBundle.constraints.map((c, i) => (
                        <li key={`icon-${c.slice(0, 20)}-${i}`}>{c}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {internalBundle.internal_notes && (
                  <div style={{ marginTop: "12px" }}>
                    <strong style={{ fontSize: "12px", color: "var(--color-text-muted)" }}>Internal Notes</strong>
                    <p style={{ fontSize: "13px", whiteSpace: "pre-wrap", marginTop: "4px" }}>
                      {internalBundle.internal_notes}
                    </p>
                  </div>
                )}
              </div>
            ) : (
              <p style={{ color: "var(--color-text-muted)" }}>No agent notes</p>
            )}
          </div>

          <div className={`${styles.splitPanel} ${styles.travelerPanel}`}>
            <div className={styles.splitTitle}>For Customer</div>
            {travelerBundle ? (
              <div>
                <div style={{ marginBottom: "12px" }}>
                  <strong style={{ fontSize: "12px", color: "var(--color-text-muted)" }}>System Context</strong>
                  <p style={{ fontSize: "13px", whiteSpace: "pre-wrap", marginTop: "4px" }}>
                    {travelerBundle.system_context || "—"}
                  </p>
                </div>
                <div style={{ marginBottom: "12px" }}>
                  <strong style={{ fontSize: "12px", color: "var(--color-text-muted)" }}>User Message</strong>
                  <p style={{ fontSize: "13px", whiteSpace: "pre-wrap", marginTop: "4px" }}>
                    {travelerBundle.user_message || "—"}
                  </p>
                </div>
                {travelerBundle.follow_up_sequence && travelerBundle.follow_up_sequence.length > 0 && (
                  <div>
                    <strong style={{ fontSize: "12px", color: "var(--color-text-muted)" }}>Follow-up Sequence</strong>
                    <ul style={{ margin: "4px 0 0 16px", fontSize: "12px" }}>
                      {travelerBundle.follow_up_sequence.map((f, i) => (
                        <li key={`fseq-${f.field_name}-${i}`}>{f.question}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ) : (
              <p style={{ color: "var(--color-text-muted)" }}>No customer message</p>
            )}
          </div>
        </div>
      </div>

      {/* Delivery Action - Wave 8 */}
      <div className={styles.deliveryActions}>
        {sendSuccess ? (
          <div className="flex items-center gap-2 text-[#3fb950] font-medium mr-4">
            <CheckCircle className="w-5 h-5" />
            Sent Successfully
          </div>
        ) : (
          <button 
            className={styles.sendButton}
            onClick={handleSendToCustomer}
            disabled={isSending || Boolean(trip && trip.review_status !== "approved" && trip.review_status !== null)}
            title={trip && trip.review_status !== "approved" ? "Trip must be approved by owner before sending" : ""}
          >
            {isSending ? (
              "Sending..."
            ) : (
              <>
                <Send className="w-4 h-4" />
                Send to Customer
              </>
            )}
          </button>
        )}
      </div>

      <div className="mt-8">
        <button
          type="button"
          className={styles.jsonToggle}
          onClick={() => setDebugRawJson(!debug_raw_json)}
        >
          {debug_raw_json ? "Hide" : "Show"} Technical Data
        </button>

        {debug_raw_json && (
          <div className={styles.jsonOutput}>
            <pre>{JSON.stringify({ internal_bundle: internalBundle, traveler_bundle: travelerBundle, review_status: trip?.review_status }, null, 2)}</pre>
          </div>
        )}
      </div>
    </div>
  );
}
