"use client";

import React, { useState } from "react";
import { useWorkbenchStore } from "@/stores/workbench";
import { ReviewControls } from "@/components/workspace/ReviewControls";
import { useTripContext } from "@/contexts/TripContext";
import type { PromptBundle } from "@/types/spine";
import type { Trip } from "@/lib/api-client";
import { CheckCircle, Send } from "lucide-react";
import Link from "next/link";
import styles from "@/components/workbench/workbench.module.css";
import { isDebugJsonAllowed } from "@/lib/privacy-controls";

interface OutputPanelProps {
  trip?: Trip | null;
  tripId?: string;
}

/**
 * OutputPanel Workflow (Wave 5 & 8)
 * 
 * Surfaces final internal/external bundles generated by the spine.
 * Wave 8 adds review controls and delivery actions.
 */
export default function OutputPanel({ trip: propTrip, tripId: propTripId }: OutputPanelProps) {
  const context = useTripContext({ optional: true });

  const trip = propTrip || context?.trip || null;
  const tripId = propTripId || trip?.id || context?.tripId || "";

  const { result_internal_bundle, result_traveler_bundle, debug_raw_json, setDebugRawJson } = useWorkbenchStore();

  const [isSending, setIsSending] = useState(false);
  const [sendSuccess, setSendSuccess] = useState(false);
  const debugJsonAllowed = isDebugJsonAllowed();

  // Fallback chain: Store (transient) > Trip (persisted)
  const internalBundle = (result_internal_bundle || trip?.internal_bundle) as PromptBundle | null;
  const travelerBundle = (result_traveler_bundle || trip?.traveler_bundle) as PromptBundle | null;
  const reviewStatus = trip?.review_status ?? null;
  const reviewBlocksSend = reviewStatus !== null && reviewStatus !== "approved";
  const policyBlocksSend = Boolean(trip?.analytics?.approvalRequiredForSend);
  const sendBlockReason =
    trip?.analytics?.sendPolicyReason ||
    (reviewBlocksSend ? "Trip must be approved by owner before sending." : "");

  const handleSendToCustomer = () => {
    setIsSending(true);
    // Mocking delivery for Wave 8
    setTimeout(() => {
      setIsSending(false);
      setSendSuccess(true);
      setTimeout(() => setSendSuccess(false), 5000);
    }, 1500);
  };

  if (!internalBundle && !travelerBundle) {
    return (
      <div className="p-6 text-center">
        <h2 className="text-ui-xl font-semibold text-text-primary">No traveler-ready output yet</h2>
        <p className="text-ui-sm text-text-muted mt-2">Build trip options and complete quote review before preparing customer-facing output.</p>
        <div className="mt-6 flex flex-wrap gap-3 justify-center">
          <Link
            href={`/trips/${tripId}/strategy`}
            className="inline-flex items-center rounded-lg border border-[var(--border-default)] px-3 py-2 text-ui-sm font-medium text-text-primary transition-colors hover:bg-elevated"
          >
            Go to Options
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8">
      {/* Review Workflow - Wave 8 */}
      {trip && (
        <ReviewControls 
          trip={trip} 
          onActionComplete={() => {
            // Parent/Context will handle data refresh
          }} 
        />
      )}

      {/* Internal vs Traveler-safe Split View */}
      <div className="border border-highlight rounded-lg p-4">
        <h3 className="text-ui-sm font-semibold text-text-primary mb-4">Agent View vs Customer View</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-lg bg-sidebar border border-highlight">
	            <h4 className="text-ui-xs font-semibold text-accent-blue uppercase tracking-wider mb-3">For You (Agent)</h4>
            {internalBundle ? (
              <div className="space-y-4">
                <div>
                  <div className="text-ui-xs font-semibold text-text-muted uppercase">Background Notes</div>
                  <p className="text-ui-sm text-text-secondary mt-1 leading-relaxed whitespace-pre-wrap">
                    {internalBundle.system_context || "-"}
                  </p>
                </div>
                <div>
                  <div className="text-ui-xs font-semibold text-text-muted uppercase">Message Preview</div>
                  <p className="text-ui-sm text-text-secondary mt-1 leading-relaxed whitespace-pre-wrap">
                    {internalBundle.user_message || "-"}
                  </p>
                </div>
                {internalBundle.constraints && internalBundle.constraints.length > 0 && (
                  <div>
                    <div className="text-ui-xs font-semibold text-text-muted uppercase">Constraints</div>
                    <ul className="mt-1 list-disc list-inside text-ui-xs text-text-muted space-y-0.5">
                      {internalBundle.constraints.map((c, i) => (
                        <li key={`icon-${c.slice(0, 20)}`}>{c}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {internalBundle.internal_notes && (
                  <div>
                    <div className="text-ui-xs font-semibold text-text-muted uppercase">Internal Notes</div>
                    <p className="text-ui-sm text-text-secondary mt-1 leading-relaxed whitespace-pre-wrap">
                      {internalBundle.internal_notes}
                    </p>
                  </div>
                )}
              </div>
            ) : (
              <p className="text-text-muted text-ui-sm">No agent notes</p>
            )}
          </div>

          <div className="p-4 rounded-lg bg-sidebar border border-highlight">
	            <h4 className="text-ui-xs font-semibold text-accent-green uppercase tracking-wider mb-3">For Customer</h4>
            {travelerBundle ? (
              <div className="space-y-4">
                <div>
                  <div className="text-ui-xs font-semibold text-text-muted uppercase">Background Notes</div>
                  <p className="text-ui-sm text-text-secondary mt-1 leading-relaxed whitespace-pre-wrap">
                    {travelerBundle.system_context || "-"}
                  </p>
                </div>
                <div>
                  <div className="text-ui-xs font-semibold text-text-muted uppercase">Message Preview</div>
                  <p className="text-ui-sm text-text-secondary mt-1 leading-relaxed whitespace-pre-wrap">
                    {travelerBundle.user_message || "-"}
                  </p>
                </div>
                {travelerBundle.follow_up_sequence && travelerBundle.follow_up_sequence.length > 0 && (
                  <div>
                    <div className="text-ui-xs font-semibold text-text-muted uppercase">Follow-up Sequence</div>
                    <ul className="mt-1 list-disc list-inside text-ui-xs text-text-muted space-y-0.5">
                      {travelerBundle.follow_up_sequence.map((f, i) => (
                        <li key={`fseq-${f.field_name}`}>{f.question}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ) : (
              <p className="text-text-muted text-ui-sm">No customer message</p>
            )}
          </div>
        </div>
      </div>

      {/* Delivery Action - Wave 8 */}
      <div className={styles.deliveryActions}>
        {policyBlocksSend && (
          <div className="mb-3 rounded-md border border-[#f85149]/40 bg-[#f85149]/10 px-3 py-2 text-ui-xs text-[#ffb4b4]">
            <strong>Send blocked by policy:</strong> {sendBlockReason}
          </div>
        )}
        {sendSuccess ? (
          <div className="flex items-center gap-2 text-[#3fb950] font-medium mr-4">
            <CheckCircle className="size-5" />
            Sent Successfully
          </div>
        ) : (
          <button 
            className={styles.sendButton}
            onClick={handleSendToCustomer}
            disabled={isSending || reviewBlocksSend || policyBlocksSend}
            title={reviewBlocksSend || policyBlocksSend ? sendBlockReason : ""}
          >
            {isSending ? (
              "Sending…"
            ) : (
              <>
                <Send className="size-4" />
                Send to Customer
              </>
            )}
          </button>
        )}
      </div>

      <div className="mt-8">
        {!debugJsonAllowed && (
          <div className="mb-2 rounded border border-amber-900/40 bg-amber-950/20 px-3 py-2 text-ui-xs text-amber-200">
            Technical Data is hidden by privacy policy. Set <code>NEXT_PUBLIC_ALLOW_DEBUG_JSON=true</code> in a secure environment to enable.
          </div>
        )}
        <button
          type="button"
          className={styles.jsonToggle}
          disabled={!debugJsonAllowed}
          onClick={() => setDebugRawJson(!debug_raw_json)}
        >
          {debug_raw_json ? "Hide" : "Show"} Technical Data
        </button>

        {debug_raw_json && debugJsonAllowed && (
          <div className={styles.jsonOutput}>
            <pre>{JSON.stringify({ internal_bundle: internalBundle, traveler_bundle: travelerBundle, review_status: trip?.review_status }, null, 2)}</pre>
          </div>
        )}
      </div>
    </div>
  );
}
