"use client";

import React, { useState } from "react";
import { useWorkbenchStore } from "@/stores/workbench";
import { ReviewControls } from "@/components/workspace/ReviewControls";
import { useTripContext } from "@/contexts/TripContext";
import type { PromptBundle } from "@/types/spine";
import type { Trip } from "@/lib/api-client";
import { CheckCircle, Send } from "lucide-react";
import styles from "@/app/workbench/workbench.module.css";

interface OutputPanelProps {
  trip?: Trip | null;
  tripId?: string;
}

/**
 * OutputPanel Workflow (Wave 5 & 8)
 * 
 * Surfaces final internal/external bundles generated by the spine.
 * Wave 8 adds review controls and delivery actions.
 */
export default function OutputPanel({ trip: propTrip, tripId: propTripId }: OutputPanelProps) {
  // Try to get trip from context if prop not provided
  let context;
  try {
    context = useTripContext();
  } catch (e) {
    // Silently continue if context unavailable
  }

  const trip = propTrip || context?.trip || null;
  const tripId = propTripId || trip?.id || context?.tripId || "";

  const { result_internal_bundle, result_traveler_bundle, debug_raw_json, setDebugRawJson } = useWorkbenchStore();

  const [isSending, setIsSending] = useState(false);
  const [sendSuccess, setSendSuccess] = useState(false);

  // Fallback chain: Store (transient) > Trip (persisted)
  const internalBundle = (result_internal_bundle || trip?.internal_bundle) as PromptBundle | null;
  const travelerBundle = (result_traveler_bundle || trip?.traveler_bundle) as PromptBundle | null;
  const reviewStatus = trip?.review_status ?? null;
  const reviewBlocksSend = reviewStatus !== null && reviewStatus !== "approved";
  const policyBlocksSend = Boolean(trip?.analytics?.approvalRequiredForSend);
  const sendBlockReason =
    trip?.analytics?.sendPolicyReason ||
    (reviewBlocksSend ? "Trip must be approved by owner before sending." : "");

  const handleSendToCustomer = () => {
    setIsSending(true);
    // Mocking delivery for Wave 8
    setTimeout(() => {
      setIsSending(false);
      setSendSuccess(true);
      setTimeout(() => setSendSuccess(false), 5000);
    }, 1500);
  };

  if (!internalBundle && !travelerBundle) {
    return (
      <div className={styles.emptyState}>
        <p>No output data for trip {tripId}. Process a trip first to generate responses.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8">
      {/* Review Workflow - Wave 8 */}
      {trip && (
        <ReviewControls 
          trip={trip} 
          onActionComplete={() => {
            // Parent/Context will handle data refresh
          }} 
        />
      )}

      {/* Internal vs Traveler-safe Split View */}
      <div className="border border-[#1c2128] rounded-lg p-4">
        <h3 className="text-sm font-semibold text-gray-200 mb-4">Agent View vs Customer View</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-lg bg-[#0a0d11] border border-[#1c2128]">
            <h4 className="text-xs font-bold text-blue-400 uppercase tracking-wider mb-3">For You (Agent)</h4>
            {internalBundle ? (
              <div className="space-y-4">
                <div>
                  <div className="text-xs font-semibold text-gray-500 uppercase">Background Notes</div>
                  <p className="text-sm text-gray-300 mt-1 leading-relaxed whitespace-pre-wrap">
                    {internalBundle.system_context || "—"}
                  </p>
                </div>
                <div>
                  <div className="text-xs font-semibold text-gray-500 uppercase">Message Preview</div>
                  <p className="text-sm text-gray-300 mt-1 leading-relaxed whitespace-pre-wrap">
                    {internalBundle.user_message || "—"}
                  </p>
                </div>
                {internalBundle.constraints && internalBundle.constraints.length > 0 && (
                  <div>
                    <div className="text-xs font-semibold text-gray-500 uppercase">Constraints</div>
                    <ul className="mt-1 list-disc list-inside text-xs text-gray-400 space-y-0.5">
                      {internalBundle.constraints.map((c, i) => (
                        <li key={`icon-${c.slice(0, 20)}-${i}`}>{c}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {internalBundle.internal_notes && (
                  <div>
                    <div className="text-xs font-semibold text-gray-500 uppercase">Internal Notes</div>
                    <p className="text-sm text-gray-300 mt-1 leading-relaxed whitespace-pre-wrap">
                      {internalBundle.internal_notes}
                    </p>
                  </div>
                )}
              </div>
            ) : (
              <p className="text-gray-500 text-sm">No agent notes</p>
            )}
          </div>

          <div className="p-4 rounded-lg bg-[#0a0d11] border border-[#1c2128]">
            <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider mb-3">For Customer</h4>
            {travelerBundle ? (
              <div className="space-y-4">
                <div>
                  <div className="text-xs font-semibold text-gray-500 uppercase">Background Notes</div>
                  <p className="text-sm text-gray-300 mt-1 leading-relaxed whitespace-pre-wrap">
                    {travelerBundle.system_context || "—"}
                  </p>
                </div>
                <div>
                  <div className="text-xs font-semibold text-gray-500 uppercase">Message Preview</div>
                  <p className="text-sm text-gray-300 mt-1 leading-relaxed whitespace-pre-wrap">
                    {travelerBundle.user_message || "—"}
                  </p>
                </div>
                {travelerBundle.follow_up_sequence && travelerBundle.follow_up_sequence.length > 0 && (
                  <div>
                    <div className="text-xs font-semibold text-gray-500 uppercase">Follow-up Sequence</div>
                    <ul className="mt-1 list-disc list-inside text-xs text-gray-400 space-y-0.5">
                      {travelerBundle.follow_up_sequence.map((f, i) => (
                        <li key={`fseq-${f.field_name}-${i}`}>{f.question}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ) : (
              <p className="text-gray-500 text-sm">No customer message</p>
            )}
          </div>
        </div>
      </div>

      {/* Delivery Action - Wave 8 */}
      <div className={styles.deliveryActions}>
        {policyBlocksSend && (
          <div className="mb-3 rounded-md border border-[#f85149]/40 bg-[#f85149]/10 px-3 py-2 text-xs text-[#ffb4b4]">
            <strong>Send blocked by policy:</strong> {sendBlockReason}
          </div>
        )}
        {sendSuccess ? (
          <div className="flex items-center gap-2 text-[#3fb950] font-medium mr-4">
            <CheckCircle className="w-5 h-5" />
            Sent Successfully
          </div>
        ) : (
          <button 
            className={styles.sendButton}
            onClick={handleSendToCustomer}
            disabled={isSending || reviewBlocksSend || policyBlocksSend}
            title={reviewBlocksSend || policyBlocksSend ? sendBlockReason : ""}
          >
            {isSending ? (
              "Sending..."
            ) : (
              <>
                <Send className="w-4 h-4" />
                Send to Customer
              </>
            )}
          </button>
        )}
      </div>

      <div className="mt-8">
        <button
          type="button"
          className={styles.jsonToggle}
          onClick={() => setDebugRawJson(!debug_raw_json)}
        >
          {debug_raw_json ? "Hide" : "Show"} Technical Data
        </button>

        {debug_raw_json && (
          <div className={styles.jsonOutput}>
            <pre>{JSON.stringify({ internal_bundle: internalBundle, traveler_bundle: travelerBundle, review_status: trip?.review_status }, null, 2)}</pre>
          </div>
        )}
      </div>
    </div>
  );
}
