#!/usr/bin/env python3
"""
Generate TypeScript interfaces from Pydantic models.

Usage:
    uv run python scripts/generate_types.py

Output:
    frontend/src/types/generated/spine_api.ts

This script reads the canonical Pydantic models from spine_api/contract.py
and generates matching TypeScript interfaces. The frontend build will
fail if UI code references types that no longer match the backend schema.
"""

import sys
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "spine_api"))
sys.path.insert(0, str(PROJECT_ROOT))

from pydantic2ts import generate_typescript_defs

OUTPUT_DIR = PROJECT_ROOT / "frontend" / "src" / "types" / "generated"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_FILE = OUTPUT_DIR / "spine_api.ts"

HEADER = """\
// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by: uv run python scripts/generate_types.py
// Source:        spine_api/contract.py + src/analytics/models.py
//
// To regenerate: uv run python scripts/generate_types.py
// ============================================================================

"""

try:
    contract_path = str(PROJECT_ROOT / "spine_api" / "contract.py")
    generate_typescript_defs(
        module=contract_path,
        output=str(OUTPUT_FILE),
        exclude=("model_config",),
    )

    with open(OUTPUT_FILE, "r") as f:
        body = f.read()

    with open(OUTPUT_FILE, "w") as f:
        f.write(HEADER + body)

    print(f"Generated TypeScript types: {OUTPUT_FILE}")
    print(f"Size: {OUTPUT_FILE.stat().st_size} bytes")

except Exception as e:
    print(f"ERROR: Failed to generate types: {e}", file=sys.stderr)
    import traceback
    traceback.print_exc()
    sys.exit(1)
