#!/usr/bin/env python3
"""Generate a portable promptfoo eval config from the KDD lane fixtures.

Per Docs/exploration/HYBRID_KDD_EXPERIMENT_2026-09-11.md §7.3/§7.5: OpenAI is
winding down its Evals product in favor of Promptfoo (see the OpenAI cookbook
"moving-from-openai-evals-to-promptfoo"). This tool ports the hybrid risk-flag
lane to a promptfooconfig.yaml so the same corpus and assertions run locally
or in CI, provider-agnostically.

What is asserted (honest scope):
- Structure contract: provider output is JSON with a `risks` array.
- The no-spurious-visa invariant (KDD §7.4 Q8): a visa_timeline_risk flag may
  only appear when the extracted packet actually carries destination facts.
  This is a cross-field property, not a per-record ground-truth label —
  visa-risk labels remain open (§7.5 item 2) and belong in the E-07 judge lane.

Usage:
    python3 tools/generate_promptfoo_config.py [--out DIR] [--models m1,m2]
    npx promptfoo eval -c <out>/promptfooconfig.yaml --no-cache
    npx promptfoo view -c <out>/promptfooconfig.yaml

The generated provider script wraps the repo's real extraction + decision
pipeline (hybrid engine ON, abstention gate active). Without provider
credentials the engine degrades to deterministic defaults which are NOT
emitted as flags (default-source skip), so the lane runs honestly in CI with
zero API cost.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

DEFAULT_MODELS = "openai:gpt-4o-mini,openai:gpt-5.6-luna"

PROVIDER_TEMPLATE = '''"""Promptfoo python provider wrapping the Waypoint OS intake decision lane.

Generated by tools/generate_promptfoo_config.py — do not hand-edit; regenerate.

Receives the raw inquiry note as `prompt`; runs the real extraction pipeline
and the hybrid decision engine (abstention gate active), and returns the
emitted risk flags plus whether destination facts exist (drives the
no-spurious-visa assertion in promptfooconfig.yaml).
"""

import json
import os
import sys

REPO = {repo!r}
if REPO not in sys.path:
    sys.path.insert(0, str(REPO))

os.environ.setdefault("TRIPSTORE_BACKEND", "file")
os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///")
os.environ["USE_HYBRID_DECISION_ENGINE"] = "1"


def call_api(prompt, options, context):
    from src.intake.extractors import ExtractionPipeline, SourceEnvelope
    import src.intake.decision as decision_mod

    decision_mod._reset_hybrid_engine()
    try:
        packet = ExtractionPipeline().extract([SourceEnvelope.from_freeform(prompt)])
        risks = decision_mod.generate_risk_flags(packet, "discovery", None)
    except Exception as exc:  # surface pipeline errors to the eval runner
        return {{"output": json.dumps({{"error": str(exc), "risks": []}})}}

    dest = packet.facts.get("destination_candidates")
    dest_value = getattr(dest, "value", None) if dest is not None else None
    payload = {{
        "risks": [
            {{"flag": r.get("flag"), "severity": r.get("severity")}}
            for r in risks
        ],
        "has_destination": bool(dest_value),
    }}
    return {{"output": json.dumps(payload)}}
'''


def load_fixture_records() -> list[dict]:
    """Mirror the harness corpus selection (KDD selection phase)."""
    records: list[dict] = []

    budget = json.loads((REPO / "data/fixtures/budget/golden_dataset.json").read_text())
    for fx in _as_list(budget):
        text = _input_text(fx)
        if text:
            records.append({"id": fx.get("fixture_id", "budget"), "note": text})

    coll = json.loads((REPO / "data/fixtures/extraction/colloquial_golden.json").read_text())
    for fx in _as_list(coll):
        text = _input_text(fx)
        if text:
            records.append({"id": fx.get("fixture_id", "coll"), "note": text})

    return records


def _as_list(data):
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        for key in ("fixtures", "records", "scenarios"):
            if isinstance(data.get(key), list):
                return data[key]
    return []


def _input_text(fx: dict) -> str:
    for key in ("raw_input", "input", "raw_note", "note", "text"):
        val = fx.get(key)
        if isinstance(val, str) and val.strip():
            return val
    return ""


NO_SPURIOUS_VISA_JS = (
    "const o = JSON.parse(output); "
    "Array.isArray(o.risks) && "
    "(o.has_destination || !o.risks.some(r => r.flag === 'visa_timeline_risk'))"
)


def build_config(models: list[str], records: list[dict]) -> dict:
    """Assemble the promptfoo eval definition."""
    assertions = [
        {"type": "is-json"},
        {"type": "javascript", "value": NO_SPURIOUS_VISA_JS},
    ]
    return {
        "description": "Waypoint OS hybrid risk-flag lane (KDD §7.3 port)",
        "prompts": ["{{note}}"],
        "providers": list(models),
        "defaultTest": {"assert": assertions},
        "tests": [
            {"description": rec["id"], "vars": {"note": rec["note"]}}
            for rec in records
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(REPO / "data/experiments/hybrid_kdd_v1"))
    parser.add_argument("--models", default=DEFAULT_MODELS)
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    records = load_fixture_records()
    if not records:
        print("no fixture records found — nothing to generate", file=sys.stderr)
        return 1

    provider_rel = "data/experiments/hybrid_kdd_v1/promptfoo_provider.py"
    provider_path = REPO / provider_rel
    provider_path.write_text(PROVIDER_TEMPLATE.format(repo=str(REPO)), encoding="utf-8")

    config = build_config(
        models=[m.strip() for m in args.models.split(",") if m.strip()],
        records=records,
    )
    config_path = out_dir / "promptfooconfig.yaml"
    _write_yaml(config, config_path, str(provider_path))

    print(f"[promptfoo] {len(records)} test cases -> {config_path}")
    print(f"[promptfoo] provider -> {provider_path}")
    venv_python = REPO / ".venv" / "bin" / "python"
    print(
        "[promptfoo] run (venv interpreter required for repo deps):\n"
        f"  PROMPTFOO_PYTHON={venv_python} npx promptfoo eval -c "
        f"{config_path} --no-cache\n"
        f"  PROMPTFOO_PYTHON={venv_python} npx promptfoo view -c {config_path}\n"
        "[promptfoo] without repo credentials the lane degrades to the "
        "deterministic pipeline (default decisions are not emitted as flags), "
        "so it is CI-safe and free."
    )
    return 0


def _write_yaml(config: dict, path: Path, provider_abs: str) -> None:
    """Minimal YAML emission without a yaml dependency (prompts are quoted)."""
    lines = [f"description: {config['description']}", "", "prompts:",]
    for p in config["prompts"]:
        lines.append(f"  - {json.dumps(p)}")
    # Absolute provider path: promptfoo resolves python:// ids against its own
    # cwd rules, and a repo-relative path mangles to filesystem-root.
    lines += ["", "providers:", f"  - python://{provider_abs}", ""]
    lines += ["defaultTest:", "  assert:"]
    for a in config["defaultTest"]["assert"]:
        lines.append(f"    - type: {a['type']}")
        if "value" in a:
            value = a["value"]
            # block scalar keeps the JS one-liner intact
            lines.append("      value: >-")
            lines.append(f"          {value}")
    lines += ["", "tests:"]
    for t in config["tests"]:
        lines.append(f"  - description: {t['description']}")
        note = json.dumps(t["vars"]["note"])
        if len(note) > 90:
            # long notes: block-scalar the var to keep the YAML readable
            raw = t["vars"]["note"]
            lines.append("    vars:")
            lines.append("      note: >-")
            for word_line in _wrap(raw):
                lines.append(f"        {word_line}")
        else:
            lines.append("    vars:")
            lines.append(f"      note: {note}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _wrap(text: str, width: int = 100) -> list[str]:
    words = text.split()
    lines: list[str] = []
    cur = ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return lines


if __name__ == "__main__":
    raise SystemExit(main())
